MODE_NONE = -1
MODE_DRAW = 0
MODE_ADD_POSITIONS = 1
MODE_REMOVE_POSITIONS = 2
MODE_MINIMUM = 3

BRUSH_MIN_SIZE = 1
BRUSH_MAX_SIZE = 100
BRUSH_SIZE_DEFAULT = 80

MHD_PARAMETERS = [True, True, True, True, True]

KMEANS_NUM_CLUSTERS = 10
KMEANS_NUM_ITERACTIONS = 10

TAB_SIZE = 250

COLOR_MODELS = ['RGB', 'HSV', 'HLS']

COLOR_SMOOTH_KERNEL_SIZE = [1, 3, 5, 7, 9, 11, 13, 15, 25, 49]

CANVAS_WIDTH = 500
CANVAS_HEIGHT = 500
CANVAS_MAXIMUM = 5000